# This file predefines a few models that the user may want to install.
sd-1/main/stable-diffusion-v1-5:
   description: Stable Diffusion version 1.5 diffusers model (4.27 GB)
   repo_id: runwayml/stable-diffusion-v1-5
   recommended: True
   default: True
sd-1/main/stable-diffusion-v1-5-inpainting:
   description: RunwayML SD 1.5 model optimized for inpainting, diffusers version (4.27 GB)
   repo_id: runwayml/stable-diffusion-inpainting
   recommended: True
sd-2/main/stable-diffusion-2-1:
   description: Stable Diffusion version 2.1 diffusers model, trained on 768 pixel images (5.21 GB)
   repo_id: stabilityai/stable-diffusion-2-1
   recommended: False
sd-2/main/stable-diffusion-2-inpainting:
   description: Stable Diffusion version 2.0 inpainting model (5.21 GB)
   repo_id: stabilityai/stable-diffusion-2-inpainting
   recommended: False
sdxl/main/stable-diffusion-xl-base-1-0:
   description: Stable Diffusion XL base model (12 GB)
   repo_id: stabilityai/stable-diffusion-xl-base-1.0
   recommended: True
sdxl-refiner/main/stable-diffusion-xl-refiner-1-0:
   description: Stable Diffusion XL refiner model (12 GB)
   repo_id: stabilityai/stable-diffusion-xl-refiner-1.0
   recommended: False
sdxl/vae/sdxl-1-0-vae-fix:
   description: Fine tuned version of the SDXL-1.0 VAE
   repo_id: madebyollin/sdxl-vae-fp16-fix
   recommended: True
sd-1/main/Analog-Diffusion:
   description: An SD-1.5 model trained on diverse analog photographs (2.13 GB)
   repo_id: wavymulder/Analog-Diffusion
   recommended: False
sd-1/main/Deliberate:
   description: Versatile model that produces detailed images up to 768px (4.27 GB)
   repo_id: XpucT/Deliberate
   recommended: False
sd-1/main/Dungeons-and-Diffusion:
   description: Dungeons & Dragons characters (2.13 GB)
   repo_id: 0xJustin/Dungeons-and-Diffusion
   recommended: False
sd-1/main/dreamlike-photoreal-2:
   description: A photorealistic model trained on 768 pixel images based on SD 1.5 (2.13 GB)
   repo_id: dreamlike-art/dreamlike-photoreal-2.0
   recommended: False
sd-1/main/Inkpunk-Diffusion:
   description: Stylized illustrations inspired by Gorillaz, FLCL and Shinkawa; prompt with "nvinkpunk" (4.27 GB)
   repo_id: Envvi/Inkpunk-Diffusion
   recommended: False
sd-1/main/openjourney:
   description: An SD 1.5 model fine tuned on Midjourney; prompt with "mdjrny-v4 style" (2.13 GB)
   repo_id: prompthero/openjourney
   recommended: False
sd-1/main/seek.art_MEGA:
   repo_id: coreco/seek.art_MEGA
   description: A general use SD-1.5 "anything" model that supports multiple styles (2.1 GB)
   recommended: False
sd-1/main/trinart_stable_diffusion_v2:
   description: An SD-1.5 model finetuned with ~40K assorted high resolution manga/anime-style images (2.13 GB)
   repo_id: naclbit/trinart_stable_diffusion_v2
   recommended: False
sd-1/controlnet/canny:
   repo_id: lllyasviel/control_v11p_sd15_canny
   recommended: True
sd-1/controlnet/inpaint:
   repo_id: lllyasviel/control_v11p_sd15_inpaint
sd-1/controlnet/mlsd:
   repo_id: lllyasviel/control_v11p_sd15_mlsd
sd-1/controlnet/depth:
   repo_id: lllyasviel/control_v11f1p_sd15_depth
   recommended: True
sd-1/controlnet/normal_bae:
   repo_id: lllyasviel/control_v11p_sd15_normalbae
sd-1/controlnet/seg:
   repo_id: lllyasviel/control_v11p_sd15_seg
sd-1/controlnet/lineart:
   repo_id: lllyasviel/control_v11p_sd15_lineart
   recommended: True
sd-1/controlnet/lineart_anime:
   repo_id: lllyasviel/control_v11p_sd15s2_lineart_anime
sd-1/controlnet/openpose:
   repo_id: lllyasviel/control_v11p_sd15_openpose
   recommended: True
sd-1/controlnet/scribble:
   repo_id: lllyasviel/control_v11p_sd15_scribble
   recommended: False
sd-1/controlnet/softedge:
   repo_id: lllyasviel/control_v11p_sd15_softedge
sd-1/controlnet/shuffle:
   repo_id: lllyasviel/control_v11e_sd15_shuffle
sd-1/controlnet/tile:
   repo_id: lllyasviel/control_v11f1e_sd15_tile
sd-1/controlnet/ip2p:
   repo_id: lllyasviel/control_v11e_sd15_ip2p
sd-1/embedding/EasyNegative:
   path: https://huggingface.co/embed/EasyNegative/resolve/main/EasyNegative.safetensors
   recommended: True
sd-1/embedding/ahx-beta-453407d:
   repo_id: sd-concepts-library/ahx-beta-453407d
sd-1/lora/LowRA:
   path: https://civitai.com/api/download/models/63006
   recommended: True
sd-1/lora/Ink scenery:
   path: https://civitai.com/api/download/models/83390
