name: Feature Request
description: Contribute a idea or request a new feature
title: '[enhancement]: '
labels: ['enhancement']
# assignees:
#   - lstein
#   - tildebyte
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!

  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: |
        Please make use of the [search function](https://github.com/invoke-ai/InvokeAI/labels/enhancement)
        to see if a similar issue already exists for the feature you want to request
      options:
        - label: I have searched the existing issues
          required: true

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: __OPTIONAL__ How could we get in touch with you if we need more info (besides this issue)?
      placeholder: ex. email@example.com, discordname, twitter, ...
    validations:
      required: false

  - type: textarea
    id: whatisexpected
    attributes:
      label: What should this feature add?
      description: Explain the functionality this feature should add. Feature requests should be for single features. Please create multiple requests if you want to request multiple features.
      placeholder: |
        I'd like a button that creates an image of banana sushi every time I press it. Each image should be different. There should be a toggle next to the button that enables strawberry mode, in which the images are of strawberry sushi instead.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternatives
      description: Describe alternatives you've considered
      placeholder: A clear and concise description of any alternative solutions or features you've considered.

  - type: textarea
    attributes:
      label: Additional Content
      description: Add any other context or screenshots about the feature request here.
      placeholder: This is a mockup of the design how I imagine it <screenshot>
