name: Close inactive issues
on:
  schedule:
    - cron: "00 4 * * *"

env:
  DAYS_BEFORE_ISSUE_STALE: 30
  DAYS_BEFORE_ISSUE_CLOSE: 14

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v8
        with:
          days-before-issue-stale: ${{ env.DAYS_BEFORE_ISSUE_STALE }}
          days-before-issue-close: ${{ env.DAYS_BEFORE_ISSUE_CLOSE }}
          stale-issue-label: "Inactive Issue"
          stale-issue-message: "There has been no activity in this issue for ${{ env.DAYS_BEFORE_ISSUE_STALE }} days. If this issue is still being experienced, please reply with an updated confirmation that the issue is still being experienced with the latest release."
          close-issue-message: "Due to inactivity, this issue was automatically closed. If you are still experiencing the issue, please recreate the issue."
          days-before-pr-stale: -1
          days-before-pr-close: -1
          exempt-issue-labels: "Active Issue"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          operations-per-run: 500
