name: style checks

on:
  pull_request:
  push:
    branches: main

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies with pip
        run: |
          pip install black flake8 Flake8-pyproject isort

      - run: isort --check-only .
      - run: black --check .
      - run: flake8
